const events = [
    {
        id: 1,
        title: "Farkında Ol; Güvende Kal",
        leader: "Sümeyye İrem Yeter",
        age: "11-15 Yaş",
        location: "Körfez Bilim ve Sanat Merkezi",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Siber Güvenlik", "Psikoloji"],
        description: "Dijital dünyadaki risklerin farkına varın! Şifrelemenin psikolojik sınırları korumakla olan benzerliğini keşfedecek, kriptoloji temelli şifre çözme oyunlarıyla dijital güvenliğinizi nasıl sağlayacağınızı öğreneceksiniz."
    },
    {
        id: 2,
        title: "Siber Kahraman Kalkanım",
        leader: "Didem Keskin Çayır",
        age: "5-8. Sınıf",
        location: "700.Yıl Osmangazi Ortaokulu",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Sanat", "Siber Güvenlik"],
        description: "Kendi dijital kalkanınızı tasarlamaya hazır mısınız? Renklerin ve sembollerin dilini kullanarak, siber güvenlik değerlerini sanatsal bir kalkan üzerine işleyecek ve kendi 'Siber Muhafız' kimliğinizi oluşturacaksınız."
    },
    {
        id: 3,
        title: "Jeolojinin Alfabesi: Kayaçlar",
        leader: "Hayriye Korkmaz",
        age: "İlkokul ve Üzeri",
        location: "Avcılar İlçe MEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Bilim", "Doğa"],
        description: "Taşların dilini çözmeye var mısın? Magmatik, tortul ve metamorfik kayaçları inceleyerek doğanın şifreli günlüğünü okuyacak, asit testleri ve büyüteçlerle 'Genç Jeolog' unvanını kazanacaksınız."
    },
    {
        id: 4,
        title: "Boncuk Boncuk Güvenlik",
        leader: "Derya Altıntaş",
        age: "10-14 Yaş",
        location: "Avcılar İlçe MEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Sanat", "Siber Güvenlik"],
        description: "Hama boncuklarıyla kendi siber kahramanını tasarla! Güçlü parolaları altın, güvenli limanları mavi boncuklarla kodlayarak dijital güvenliğini fiziksel bir anahtarlığa dönüştür."
    },
    {
        id: 5,
        title: "Robot Zihni ile Dijital Şifre Avı",
        leader: "Suzan Atmaca",
        age: "Ortaokul",
        location: "Derince BİLSEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Yapay Zeka", "Oyun"],
        description: "3D robot 'Zihni' ile tanışın! Medya okuryazarlığı labirentinde dijital şifreleri çözecek, yapay zeka destekli ipuçlarıyla güvenli ve güvensiz alanları ayırt etmeyi öğreneceksiniz."
    },
    {
        id: 6,
        title: "Dijital Denge Yolculuğu",
        leader: "Gülay Turğut",
        age: "10-14 Yaş",
        location: "Hacı Seyit Taşan İlkokulu",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Drama", "Psikoloji"],
        description: "Ekran bağımlılığına karşı iradeni güçlendir! Emojilerle duygu analizi yapacak, interaktif drama oyunlarıyla dijital dünyada zaman yönetimini ve dengede kalmayı öğreneceksiniz."
    },
    {
        id: 7,
        title: "Veri Dedektifleri",
        leader: "Tuğçe Höbek",
        age: "10 Yaş ve Üzeri",
        location: "Orbay Ortaokulu",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Oyun", "Siber Güvenlik"],
        description: "İnternette bıraktığın ayak izlerini takip et! Dedektif ekipleri kurarak dijital izlerinizi analiz edecek, güvenli ve riskli verileri iplerle birbirine bağlayarak dev bir veri haritası oluşturacaksınız."
    },
    {
        id: 8,
        title: "İrrasyonel Şifreleme",
        leader: "Ahmet Harun Açık",
        age: "Ortaokul ve Üzeri",
        location: "İstanbul Teknik Üniversitesi",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Kriptoloji", "Matematik"],
        description: "Casusların gizli dilini öğrenin! Harf ve sayı eşleşmeleriyle kendi kripto mesajlarınızı yazacak, arkadaşlarınızın şifrelerini çözerek analitik düşünme becerilerinizi geliştireceksiniz."
    },
    {
        id: 9,
        title: "Siber Yolculukta Drama",
        leader: "Ayşe Çağdaş",
        age: "5-6 Yaş (Okul Öncesi)",
        location: "İTÜ Minik Denizciler",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Drama", "Okul Öncesi"],
        description: "Minik denizciler siber okyanusa açılıyor! Oyunlar ve canlandırmalarla internetin görünmez ağlarını keşfedecek, güvenli ve güvensiz durumları eğlenceli bir şekilde öğreneceğiz."
    },
    {
        id: 10,
        title: "Kripto-Labirent: Acil Çözüm Takımı",
        leader: "Elif Dilek",
        age: "Ortaokul",
        location: "Derince BİLSEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Kriptoloji", "Oyun"],
        description: "Siber evreni kurtarmak için 20 dakikanız var! Sezar Çarkı ve Pigpen şifrelerini çözerek, UV ışıklarla gizli mesajları bulun ve 'KARMA' virüsünü durdurun."
    },
    {
        id: 11,
        title: "Dijital Şehrin Trafik Işıkları",
        leader: "Yüksel Canbolat",
        age: "Okul Öncesi",
        location: "Barboros Anaokulu",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Okul Öncesi", "Oyun"],
        description: "Dijital dünyada ne zaman durmalı, ne zaman geçmelisin? Kırmızı, Sarı ve Yeşil kartlarla dijital güvenliği öğrenecek, müzikli oyunlarla güvenli internet kurallarını pekiştireceğiz."
    },
    {
        id: 12,
        title: "Dil Dedektifi ile Oltaya Gelme",
        leader: "Pınar Uşar",
        age: "Ortaokul",
        location: "Ressam Osman Hamdi Bey OO",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Siber Güvenlik", "Dil Bilgisi"],
        description: "Sahte mesajları dil hatalarından yakalayın! Bir 'Dil Dedektifi' olarak oltalama (phishing) tuzaklarını inceleyecek, yazım yanlışları ve şüpheli linkleri analiz ederek dijital dolandırıcılara geçit vermeyeceksiniz."
    },
    {
        id: 13,
        title: "Siber Memory",
        leader: "Esengül Eryılmaz",
        age: "6-10 Yaş",
        location: "Ressam Osman Hamdi Bey OO",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Oyun", "Hafıza"],
        description: "İnternet işaretlerini ne kadar iyi tanıyorsun? Dijital dünyadaki sembolleri eşleştirerek hafızanızı test edin, doğru eşleşmeleri bularak sürpriz ödüller kazanın."
    },
    {
        id: 14,
        title: "Sezar Çarkı Atölyesi",
        leader: "Sıtkı Bilal Doğan",
        age: "9 Yaş (İlkokul)",
        location: "Kocaeli Bilim Merkezi",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Kriptoloji", "Tarih"],
        description: "Roma imparatorlarının gizli haberleşme yöntemini keşfedin! Kendi Sezar Çarkınızı kullanarak mesajları şifreleyecek ve arkadaşlarınızla güvenli, gizli notlar paylaşacaksınız."
    },
    {
        id: 15,
        title: "Siber Güvenlik Masalları",
        leader: "Elmas Gezer",
        age: "4-12 Yaş",
        location: "İzmit BİLSEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Sanat", "Masal"],
        description: "Ejderhalar yerine dijital virüslerle savaşan kahramanlar! İnteraktif masal anlatımıyla siber dünyayı keşfedecek, kendi dijital kalkanınızı boyayarak hikayenin bir parçası olacaksınız."
    },
    {
        id: 16,
        title: "Dijital Dedektif Atölyesi",
        leader: "Aysel Sürücü",
        age: "11-13 Yaş",
        location: "Körfez BİLSEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Siber Güvenlik", "Oyun"],
        description: "İnternet sokaklarındaki tuzakları temizlemeye hazır mısın? Güvenli ve tehlikeli durumları ayırt edecek, mıknatıslı panolarda kırılması imkansız 'Süper Parola'nızı tasarlayacaksınız."
    },
    {
        id: 17,
        title: "Gerçek mi Yapay Zeka mı?",
        leader: "Muhammed Gökhan Perçem",
        age: "9 Yaş ve Üzeri",
        location: "Kocaeli Üniversitesi",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Yapay Zeka", "Teknoloji"],
        description: "Gözlerinize ne kadar güveniyorsunuz? Deepfake ve yapay zeka videolarını analiz edecek, fiziksel hataları ve görsel tutarsızlıkları bularak dijital sahteciliği tespit etmeyi öğreneceksiniz."
    },
    {
        id: 18,
        title: "Eğlenceli Şifreleme: Kaydırmalı Algoritma",
        leader: "Nuriye Aşut Önal",
        age: "Ortaokul",
        location: "Körfez BİLSEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Kriptoloji", "Algoritma"],
        description: "Mesajlarınız başkasının eline geçse bile okunamasın! Renkli şifre diskleri ve kaydırmalı algoritmalarla kendi gizli dilinizi oluşturun, dijital dünyada bilgilerinizi zırh gibi koruyun."
    },
    {
        id: 19,
        title: "Oltaya G(e)lmeyen Kelimeler: Tabure",
        leader: "Ayşenur Öztürk Akcin",
        age: "10-15 Yaş",
        location: "Ressam Osman Hamdi Bey OO",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Mühendislik", "Geri Dönüşüm"],
        description: "Eski kitaplar ve kağıtlar ne kadar güçlü olabilir? Atık malzemeleri rulo yaparak sağlam tabureler inşa edecek, parçaların birleşerek nasıl güçlü bir bütün oluşturduğunu deneyimleyeceksiniz."
    },
    {
        id: 20,
        title: "Siber Kahramanlar Maske Atölyesi",
        leader: "Bilgen Akgül",
        age: "10-14 Yaş",
        location: "Şehit Halil İbrahim Yiğit OO",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Sanat", "Siber Güvenlik"],
        description: "İçindeki siber kahramanı ortaya çıkar! Yüz boyama ve maske tasarımıyla kendi dijital süper gücünü (Şifre Koruyucu, Veri Kalkanı) yansıt ve siber ormanın koruyucusu ol."
    },
    {
        id: 21,
        title: "Kodlama ile Şifreleme",
        leader: "Kübra Aycan Kavlak",
        age: "Ortaokul",
        location: "Gebze 23 Nisan BİLSEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Kodlama", "Matematik"],
        description: "0 ve 1'lerin dünyasına yolculuk! Basit kodlama mantığıyla kendi şifreleme algoritmanızı yazacak, bilgisayarların verileri nasıl sakladığını uygulamalı olarak öğreneceksiniz."
    },
    {
        id: 22,
        title: "Dijital Ebeveynlik: Bir Çay Molası",
        leader: "Melek Candemir",
        age: "Yetişkin",
        location: "Gebze 23 Nisan BİLSEM",
        date: "-WIP-",
        time: "Programda Belirtilecek",
        tags: ["Söyleşi", "Psikoloji", "Ebeveyn"],
        description: "Mükemmel ebeveyn yoktur, bilinçli ebeveyn vardır. Dijital dünyada çocuk yetiştirmenin zorluklarını, ekran süresi yönetimini ve güvenli interneti samimi bir sohbet ortamında konuşuyoruz."
    },
    {
        id: 23,
        title: "Şifre Fabrikası",
        leader: "Müzeyyen Tekerek",
        age: "Ortaokul",
        location: "Gebze 23 Nisan BİLSEM",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Oyun", "Matematik"],
        description: "Fabrikada alarm çalıyor! En hızlı ve en güçlü şifreyi kim üretecek? Harf, rakam ve sembol küplerini kullanarak siber saldırılara karşı en dayanıklı zırhı ören siz olun."
    },
    {
        id: 24,
        title: "Dijital Kriz: Fikir Çarpıştırma",
        leader: "Muhammed Eren Karaoğlu",
        age: "Lise ve Üzeri",
        location: "Bağımsız",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Siber Güvenlik", "Tartışma"],
        description: "Bir dijital kriz anında ne yapardınız? Verilen senaryolar üzerinden argümanlarınızı geliştirin, karşıt fikirleri çürütün ve krizden en güvenli çıkış yolunu tasarlayın."
    },
    {
        id: 25,
        title: "Elementlerin Gücü: Bilim Laboratuvarı",
        leader: "Seracettin Osmanoğlu",
        age: "Tüm Yaşlar",
        location: "Kocaeli Bilim Merkezi",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Bilim", "Fizik"],
        description: "Ateşi avucunuzda tutmaya hazır mısınız? Sıvı azot gösterileri, damacana bükme deneyi ve kimyasal tepkimelerle fiziğin ve kimyanın büyüleyici dünyasına tanık olun."
    },
    {
        id: 26,
        title: "Kripto ve Siber Gelecek: DNA",
        leader: "Dr. Hasan Koca",
        age: "Lise ve Üzeri",
        location: "Kocaeli Bilim Merkezi",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Biyoloji", "Kriptoloji"],
        description: "Geleceğin şifreleri hücrelerimizde saklı! DNA'nın dörtlü yapısını (A,C,G,T) kullanarak biyokriptografik şifreleme yapacak, biyoloji ve matematiğin güvenli birleşimini keşfedeceksiniz."
    },
    {
        id: 27,
        title: "Sistemi Kurtar Güvende Kal",
        leader: "Ayşe Gültepe",
        age: "Ortaokul ve Lise",
        location: "Düzce Borsa İstanbul MTAL",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Oyun", "Siber Güvenlik"],
        description: "Dijital labirentten çıkış yolunu bul! Siber timler halinde kilitli kutuları açın, QR kod görevlerini tamamlayın ve dijital ayak izlerinizi temizleyerek sistemi kurtarın."
    },
    {
        id: 28,
        title: "Bilim Gösterisi",
        leader: "Emre Yıldız",
        age: "Tüm Yaşlar",
        location: "Kocaeli Bilim Merkezi",
        date: "2-3-4 Ekim",
        time: "Gösteri Saatlerinde",
        tags: ["Etkinlik", "Bilim", "Gösteri"],
        description: "Bilim hiç bu kadar heyecanlı olmamıştı! Görsel şölen eşliğinde gerçekleşen deneyler, sıvı azot bulutları ve basınç şovlarıyla unutulmaz bir bilim gösterisi sizleri bekliyor."
    },
    {
        id: 29,
        title: "Bileğimde Şifreleme",
        leader: "GTÜ Bilim Ekibi",
        age: "İlkokul",
        location: "Gebze Teknik Üniversitesi",
        date: "2-3-4 Ekim",
        time: "10:00 - 16:00",
        tags: ["Etkinlik", "Sanat", "Siber Güvenlik"],
        description: "Şifrenizi bileğinizde taşıyın! İkili kod sistemini veya renkli boncukları kullanarak kendi benzersiz şifrenizi bir bilekliğe dönüştürün ve güvenliğinizi yanınızdan ayırmayın."
    }
];
